baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme="PaperMod"

[params]
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowShareButtons = true
    ShowTags = true
    ShowHomeContent = true