baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Alray Blog'

theme="PaperMod"

[params]
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowShareButtons = true
    ShowTags = true
    ShowHomeContent = true