baseURL = 'https://alrayqiu.github.io/'
languageCode = 'zh-cn'
title = 'Alray Doc'

[module]
  [[module.imports]]
    path = 'github.com/google/docsy'

theme = "docsy"

[params]
  description = "这是一个使用 Docsy 构建的 Hugo 文档站"
  ui.sidebar_menu_compact = true
  ui.navbar_logo = true
  ui.footer_about_enable = true

[markup.goldmark.renderer]
  unsafe = true