

baseURL = 'https://alrayqiu.github.io/'
languageCode = 'zh-cn'
title = 'Alray Doc'
sectionPagesMenu = "main"


[module]
  [[module.imports]]
    path = 'github.com/google/docsy'

theme = "docsy"

[params]
  description = "这是一个使用 Docsy 构建的 Hugo 文档站"

  
[params.katex]
  enable = true


[params.taxonomy]
  taxonomyCloud = ["tags", "categories"]
  taxonomyCloudTitle = ["标签云", "分类"]
  taxonomyPageHeader = ["tags", "categories"]

[params.ui]
  sidebar_search_disable = true
  sidebar_menu_compact = true
  ul_show = 1
  sidebar_menu_foldable = true
  sidebar_cache_limit = 1000  
  navbar_logo = true
  footer_about_enable = true
  showLightDarkModeMenu = true

[params.search]
  enabled = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
[markup]
  [markup.highlight]
      style = "onedark"


