baseURL = 'https://alrayqiu.github.io/'
languageCode = 'zh-cn'
title = 'Alray Doc'
sectionPagesMenu = "main"


[module]
  [[module.imports]]
    path = 'github.com/google/docsy'

theme = "docsy"

[params]
  description = "这是一个使用 Docsy 构建的 Hugo 文档站"
  ui.sidebar_menu_compact = true
  ui.navbar_logo = true
  ui.footer_about_enable = true
  ui.showLightDarkModeMenu = true
  
[params.search]
  enabled = true

[markup.goldmark.renderer]
  unsafe = true
[markup]
  [markup.highlight]
      style = "onedark"

[[menu.main]]
  name = "Navigation"
  url = "/Navigation/"
  weight = 1

[[menu.main]]
  name = "AutoAim"
  url = "/AutoAim/"
  weight = 2
